### ISSUE TITLE
Can tinker-dash work with GeckoDriver ?

### ISSUE THREAD

**Issue by anthonyblanchflower** [anthonyblanchflower/tinker-dash#1]
tinker-dash was developed to work with Chrome using a binary of the chromedriver ARM web driver (made available by the Electron project). I believe a recent Chrome update has rendered the latest available chromedriver ARM binary unusable. Could someone test if tinker-dash can be used with Firefox and their geckodriver ARM web driver: https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-arm7hf.tar.gz

**Comment by laurence-hubbard** [comment]
Hi @anthonyblanchflower !

I've submitted a fix. Please could you add me as the assignee.
